spring:
  r2dbc:
    driver-class-name: org.postgresql.Driver
    url: r2dbc:postgresql://localhost:5432/chatclientdb
    username: postgres
    password: Vaifery111


  application:
    name: client

server:
  port: 7015

variables:
  SECRET_KEY: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"

