spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/chatclientdb
    username: postgres
    password: Vaifery111
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-circular-references: true
  application:
    name: client

server:
  port: 7015



